<table>
    <tr>
        <td width="150">Pfadiname</td>
        <td><?php echo $this->data['pfadiname']; ?></td>
    </tr>
    <tr>
        <td width="150">Vorname</td>
        <td><?php echo $this->data['vorname']; ?></td>
    </tr>
    <tr>
        <td width="150">Nachname</td>
        <td><?php echo $this->data['nachname']; ?></td>
    </tr>
    <tr>
        <td width="150">Mail</td>
        <td><?php echo $this->data['mail']; ?></td>
    </tr>
</table>
<hr />
<table>
    <tr>
        <td width="150">Bank</td>
        <td><?php echo $this->data['bank']; ?></td>
    </tr>
    <tr>
        <td width="150">IBAN</td>
        <td><?php echo $this->data['iban']; ?></td>
    </tr>
</table>
<hr />
<table>
    <tr>
        <td width="150">Angebot</td>
        <td><?php echo $this->data['angebot-nr']; ?></td>
    </tr>
</table>


