<div class="jumbotron">
    <h1>Pfadi Luzern - Finanzen</h1>
    <p>
        Diese Seite soll die Abläufe rund um Finanzen vereinfachen.
    </p>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Vorstand / Kanal</h3>
            </div>
            <div class="panel-body">
                <p>
                    Du kannst deine Spesenabrechnung online erledigen.
                </p>

                <a href="<?php echo $this->url('spesen'); ?>" class="btn btn-success pull-right">
                    <i class="glyphicon glyphicon-chevron-right"></i> Spesenabrechnung
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Coach</h3>
            </div>
            <div class="panel-body">
                <p>
                    Du kannst deine J+S Coach-Entschädigung online beantragen.
                </p>

                <a href="<?php echo $this->url('js-angebot'); ?>" class="btn btn-success pull-right">
                    <i class="glyphicon glyphicon-chevron-right"></i> J+S Angebot melden
                </a>
            </div>
        </div>
    </div>
</div>
